name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt

      - name: Run Django Migrations
        run: |
          python manage.py migrate

      - name: Run Tests with django
        run: |
          python manage.py test

      - name: Check Code Formatting with Black
        run: |
          black --check .

      - name: Check Import Order with isort
        run: |
          isort --check-only .

      - name: Lint the Code with Flake8
        run: |
          flake8 .
